### ISSUE TITLE
pycgbuilder crashing with "pie() got an unexpected keyword argument 'normalize'"

### ISSUE THREAD

**Issue by ricalessandri** [marrink-lab/pycgbuilder#7]
Do you know why this happens? I'm trying on my laptop (macOS) and I thought I remember `pycgbuilder` worked some time ago... but I might remember wrong.

I can source a pdb or SMILES but then when I try to click on an atom `pycgbuilder` crashes with the following error:
```
/Users/riccardo/miniconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/riccardo/miniconda3/lib/python3.8/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/Users/riccardo/miniconda3/lib/python3.8/site-packages/pycgbuilder-0.1.0-py3.8.egg/pycgbuilder/mapping_widget.py", line 134, in redraw
    self.draw_mapping()
  File "/Users/riccardo/miniconda3/lib/python3.8/site-packages/pycgbuilder-0.1.0-py3.8.egg/pycgbuilder/mapping_widget.py", line 158, in draw_mapping
    pie = self.ax.pie(sizes, center=position, radius=self.atom_radius, normalize=True,
  File "/Users/riccardo/miniconda3/lib/python3.8/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
TypeError: pie() got an unexpected keyword argument 'normalize'
Abort trap: 6
```

**Comment by pckroon** [comment]
Curious, I can't reproduce the issue on my machine.

What's your version of matplotlib and python? I have:
matplotlib: 3.4.2
Python: 3.8.1

**Comment by ricalessandri** [comment]
matplolib: 3.2.2
Python 3.8.5

Maybe it's matplolib?

**Comment by pckroon** [comment]
Jup. Once I downgrade my matplotlib to 3.2.2 I get the same issue.
Upgrade your matplotlib and it should be resolved.
